### ISSUE TITLE
no AttrValue in attr

### ISSUE THREAD

**Issue by nebelgrau77** [drogue-iot/drogue-microbit#2]
Hi there,

I'm trying to use your example with micro:bit, but it won't compile: there doesn't seem to be `AttrValue` in `attr`. I checked the `rubble` code and in fact couldn't find it.

**Comment by lulf** [comment]
👋  l think the reason is that rubble changed, and the example did not have a Cargo.lock nor fixed it's dependency version. I've put in a fixed dependency rev now, so it compiles again. Thanks for reporting this!

FWIW, we're having an updated BLE example for microbit here https://github.com/drogue-iot/drogue-device/tree/main/examples/nrf52/microbit/ble-temperature

**Comment by nebelgrau77** [comment]
Great, I'll give it a try! 

I only have the v1 micro:bit, but I can try adapting the nrf52 example to my Arduino BLE Sense. Thanks!
